server:
    port: 8761
spring:
    cloud:
        config:
            uri: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

res:
  marketNewsList:
    - id: A
      topic: China
      content: The detail
      publishDate: 2018-08-18
    - id: B
      topic: Japan
      content: The detail 2
      publishDate: 2018-08-17